# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 92cf160e5dc647f357a76fb55c9338bb850df16eb1bbdcd54e1651225d58ddb3058edf3f8cadc9efddfb750d56def056798fa4f9e1342108c35ded54e4106e9d

test:
  secret_key_base: 1ba06d23f6ac1f405c3a37149ecc6d303afeb7149dd05550a899c4934c9d73c6a604032920754b11c688898c607282df24e0a028becefe0f29f42ddd2421c48d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
